### Register a new user with Authorization
POST http://localhost:8000/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "+916380615171",
    "password": "Sanjay@123"
}

### Login with Authorization
GET http://localhost:8000/getPro/ HTTP/1.1
Content-Type: application/json

### Get all products
GET http://localhost:8000/getCat/ HTTP/1.1
Content-Type: application/json

### Get all categories
GET http://localhost:8000/getProduct/5/ HTTP/1.1
Content-Type: application/json

### Get product by id
GET http://127.0.0.1:8000/getWholeSaleProducts/ HTTP/1.1
Content-Type: application/json
Authorization: Token 7ea3e1cc9f94d292c30867066a04e3de6ec4ebef
