# Generated by Django 5.0.6 on 2024-05-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hexcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
