# Generated by Django 5.0.6 on 2024-05-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_image_remove_product_images_product_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('products', models.ManyToManyField(blank=True, to='home.product')),
            ],
        ),
    ]
