# Generated by Django 5.0.6 on 2024-05-15 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_color_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
