# Generated by Django 5.0.6 on 2024-05-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cartitem_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(blank=True, to='home.cartitem'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
