# Generated by Django 5.0.6 on 2024-05-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='doorNo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
