# Generated by Django 5.0.6 on 2024-05-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
