# Generated by Django 5.0.6 on 2024-05-31 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_address_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_valid',
        ),
    ]
