# Generated by Django 5.0.6 on 2024-06-04 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_address_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='otpst',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 8, 0, 0, 594450, tzinfo=datetime.timezone.utc)),
        ),
    ]
