# Generated by Django 5.0.6 on 2024-06-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_customer_otpst'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='chest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='hip',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='pant_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='shoulder',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='sleev_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='thigh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='top_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='waist',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
