# Generated by Django 5.0.6 on 2024-06-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_size_chest_size_hip_size_pant_length_size_shoulder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gstNo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
