# Generated by Django 5.0.6 on 2024-06-09 18:40

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_customer_gstno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gstNo',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[home.models.validate_gst]),
        ),
        migrations.CreateModel(
            name='BulkProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_qty', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
