# Generated by Django 5.0.6 on 2024-06-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_customer_gstno_bulkproductitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discription', models.TextField(blank=True, null=True)),
                ('marketPrice', models.FloatField()),
                ('wholeSellPrice', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_items', models.ManyToManyField(blank=True, to='home.bulkproductitem')),
            ],
        ),
    ]
