# Generated by Django 5.0.6 on 2024-06-10 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_bulkproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkproductitem',
            name='bulk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bulkproducts'),
        ),
    ]
