# Generated by Django 5.0.6 on 2024-06-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_bulkproductitem_bulk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkproducts',
            name='bulk_items',
        ),
    ]
