# Generated by Django 5.0.6 on 2024-06-10 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_bulkproducts_bulk_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkproductitem',
            name='bulk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bulkproducts'),
        ),
    ]
