# Generated by Django 5.0.6 on 2024-06-11 06:55

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_bulkproductitem_bulk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gstNo',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, validators=[home.models.validate_gst]),
        ),
    ]
