# Generated by Django 5.0.6 on 2024-06-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_customer_gstno'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkproducts',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='bulk_pic/'),
        ),
    ]
