import Navbar from "./Components/Navbar"
import FootBar from "./Components/footer"
import "./globals.css"
import 'swiper/swiper-bundle.css';
// import "./assets/js/main.js"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Home Page</title>
        <link
          rel="stylesheet"
          href="https://cdn-uicons.flaticon.com/2.0.0/uicons-regular-straight/css/uicons-regular-straight.css"
        />

        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
        />

      </head>
      <body>
        <Navbar/>
        {children}
        <FootBar/>
      </body>
    </html>
  )
}
